export const CONDENSER_TOPIC = "esp32/d150/ctemperature"
export const KETTLE_TOPIC = "esp32/d150/ktemperature"
export const PUMP_TOPIC = "esp32/d150/statepump"
export const HEATER_TOPIC = "esp32/d150/dcheater"
export const PROGRESS_TOPIC = "dprogress"
export const HEATER_SETTING_TOPIC = "redmi6pro"
export const PUMP_SETTING_TOPIC = "redmi6pro2"