# Generated by Django 3.0.2 on 2020-02-05 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='distillerID',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='record',
            name='topic',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='DisitllerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=50)),
                ('capacity', models.CharField(blank=True, max_length=10)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distillers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
