# Generated by Django 3.0.2 on 2020-02-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20200205_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='distillerrecord',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
