# Generated by Django 3.0.2 on 2020-02-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_distillerrecord_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sapspecs',
            name='owner',
        ),
        migrations.AddField(
            model_name='record',
            name='sap_brix',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='record',
            name='sap_date_collected',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='sap_fermentation',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='record',
            name='sap_origin',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='record',
            name='sap_volume',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='RecordBuffer',
        ),
        migrations.DeleteModel(
            name='SapSpecs',
        ),
    ]
