# Generated by Django 3.0.2 on 2020-02-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20200207_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distillerrecord',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='distillerrecord',
            name='topic',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
