# Generated by Django 3.0.2 on 2020-05-12 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_auto_20200207_1443'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistillerRecord',
        ),
    ]
