# Generated by Django 3.0.2 on 2020-07-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_delete_distillerrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='output_volume',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
    ]
