# Generated by Django 3.0.2 on 2020-07-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_auto_20200706_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='sap_remarks',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
